### ISSUE TITLE
KA и Punto Switcher

### ISSUE THREAD

**Issue by Lichtenshtein** [AndreyKaiu/Keybord_Assistant#1]
Keybord Assistant версии 2.0.2 изменяет регистр исправляемых Punto Switcher'ом слов на нижний.

**Comment by AndreyKaiu** [comment]
> Keybord Assistant версии 2.0.2 изменяет регистр исправляемых Punto Switcher'ом слов на нижний.

Спасибо за замечание, возможно оно очень кому-то будет важно.
На Windows 7, установлена «Punto Switcher 4.4» и отключено переключение языков у Punto, так как «Keybord_Assistant» и сам это умеет. Автопереключение Punto работает. Комбинации клавиш переключения Shift+Break тоже работает и регистр не изменяет. 
Проблема не обнаружил согласно тех настроек, что менял. Что-то можно отключить в «Keybord_Assistant», пробовал менять это:
«; change case to lower by Alt+Pause (upper Alt+Shift+Pause)
; =ru= изменить регистр на нижний по Alt+Pause (верхний Alt+Shift+Pause)
Alt_Pause=1» 

Особо не влияло.
И важно помнить, что эти две программы могут конкурировать по горячим клавишам, пробуйте где-то отключать или в крайнем случае меняйте код «Keybord_Assistant».

**Comment by Lichtenshtein** [comment]
Windows 10, Punto Switcher 4.4.3. Автоматическое переключение языков у Punto, или ручное - без разницы - Keybord_Assistant меняет регистр на нижний. Переключение в Punto назначено на ctrl+space, все другие сочетания клавиш отключены.

Перекачал Keybord_Assistant с github, c дефолтными настройками регистр тоже меняется.

Приложу мой конфиг:

```
[MAIN]

FileLocalization=Russian.ini
HelpFile=help\Help_Russian2.png
ShowToolTip=1
PlaySound=0
SoundLevelAtStartup=
TimeSwitchLayout=250
LShift_RShift_CapsLock=1
TimeSwitchCapsLock=300
FileSoundCapsLockON=CapsLockON.wav
FileSoundCapsLockOFF=CapsLockOFF.wav
FileSoundMouseStuckOFF=StuckOFF.wav
FileSoundMouseStuckON=StuckON.wav
TestMode=0

[PLACE_FOR_SECTION_KEYBOARDS]
[KEYBOARDS]

0x04090409, en_US, EN, 01.wav, Английский (США), US
0x04190419, ru_RU, RU, 02.wav, Русский (Россия), Russian

[LAYOUT_LIST_1]

0x04190419, ru_RU

[LAYOUT_LIST_2]

0x04090409, en_US

[LAYOUT_LIST_3]

0x04190419, ru_RU
0x04090409, en_US

[LAYOUT_LIST_4]

0x04190419, ru_RU
0x04090409, en_US

[LAYOUT_LIST_5]
[LAYOUT_LIST_6]
[LAYOUT_LIST_7]
[LAYOUT_LIST_8]
[CAPSLOCK_OPTIONS]

CapsLockReassign=
CapsLockOption=Disable

[LSHIFT_OPTIONS]

LShiftOption=0

[RSHIFT_OPTIONS]

RShiftOption=

[LCTRL_OPTIONS]

LCtrlOption=

[RCTRL_OPTIONS]

RCtrlReassign=
RCtrlOption=Disable

[LALT_SPACE_OPTIONS]

LAltSpaceOption=

[LALT13]

LAlt13_Enable=1
LAlt0="
LAlt0=Disable
LAlt1=Disable
LAlt2=Disable
LAlt3=Disable
LAlt4=Disable
LAlt5=Disable
LAlt6=Disable
LAlt7=Disable
LAlt8=₽
LAlt9=:
LAlt10=;
LAlt11=— 
LAlt12= —\s
LAlt13=́

[RALT_OPTIONS]

RAltReassign=Disable
RAltOption=3
RAltAddCursor=1
RAltAddMouse=1
RAltAddChars=1
RAlt_Shift_1=°
RAlt_Shift_2=«
RAlt_Shift_3=»
RAlt_Q=ї
RAlt_Shift_Q=Ї
RAlt_W=ӂ
RAlt_Shift_W=Ӂ
RAlt_A=ў
RAlt_Shift_A=Ў
RAlt_Z=ґ
RAlt_Shift_Z=Ґ
RAlt_X=є
RAlt_Shift_X=Є
RAlt_C=,\s
RAlt_Shift_C=;\s
RAlt_B=і
RAlt_Shift_B=І
RAlt_Space= 
RAlt_Shift_Space= 

[RWIN_OPTIONS]

RWinReassign=Disable
RWinOption=Disable
RWinBirmanLayout=1
RWin_Space= 
RWin_Shift_Space= 

[ADDITIONALLY]

Ctrl_Alt_V=0
Alt_Pause=0
Alt_ScrollLock=1
FileTranslit_1=Cyr_to_Eng.ini
Alt_Shift_ScrollLock=1
FileTranslit_2=Cyr_to_FileNameEng.ini
Alt_Win_ScrollLock=1
RAlt_BackSpace=0

```

> в крайнем случае меняйте код «Keybord_Assistant».

У меня нет догадок что может вызывать конфликт, поэтому и создал issue.

К слову, в раскладке не хватает удобной кнопки для символов : (двоеточие) и ; (точка с запятой).

Ещё если пользоваться не скомпилированной версией, то нажатие стоп\старт в меню вызывает ошибку:

```
Error in #include file "bla-bla\Keybord Assistant 2\MN_Menu.ahk":
     Failed attempt to launch program or document:
Action: <RAltRWin.exe>
Params: <>

Specifically: Не удается найти указанный файл.


	Line#
	704: Pause,Toggle
	706: }
	707: Else
	708: {
	710: SetDisableLockWorkstationRegKeyValue( 0 )  
	713: SetKeyDelay,-1
	714: SendInput,{LCtrl Up}{RCtrl Up}{LWin Up}{RWin Up}{LAlt Up}{RAlt Up}{LShift Up}{RShift Up}{vkB6 Up}{vkA9 Up}{Tab Up}
--->	717: Run,RAltRWin.exe
	718: Pause,Toggle
	720: }
	722: Return
	727: {
	730: IniRead,var,localization\%MN_FILE_INI%,LIST,L1
	731: if ( var <> "ERROR" )  
	732: {

The current thread will exit.
```

**Comment by AndreyKaiu** [comment]
> Приложу мой конфиг:
> LShiftOption=0

Нежелательно писать 0, когда можно задавать из 1 до 8 или пусто.

> У меня нет догадок что может вызывать конфликт, поэтому и создал issue.

Мой код проблемно работает с Punto Switcher, так как совместная работа не предназначена, уж тут могут быть конфликты. Думаете Punto Switcher хорошо оптимизирована? Увы, вот для 4.4.4 пишут «Усовершенствовали работу с Office2013 и Office2016 на Win7x32» я же задолбался как-то заставить не глючит этот офис...перешел на другую версию и всё. А тут тоже тестировал и видел зависания у переключения как у вас по LCtrl + Space, если очень быстро переключать то зависает у меня LCtrl в Office2013 64 бит с обновлениями по 2022 год   (моя программа выключена, это именно у них глючит Punto Switcher, у него скорость переключения похуже, чем у меня, а это мне важно)


> К слову, в раскладке не хватает удобной кнопки для символов : (двоеточие) и ; (точка с запятой).

Скопируйте из нового файла настроек секцию «[LALTADD14]» там:
еще 14 горячих комбинации для LAlt+[  LAlt+]  LAlt+;  LAlt+'  LAlt+,  LAlt+.  LAlt+/
Это как вариант, чтобы что в русскому или англ. не думать а постоянно точка, запятая, точка с запятой была всегда по одинаковому нажатию. Конечно, вы можете изменить из настроек под себя.
У меня проблемы нет, так как в русском нормально набираю, что; что : так как подвижность пальцев развита, да и скоростной набор есть. А вот если код бить, то там в основном английский и проблем нет, а переключение только между 2 языками у меня по правому альту, так что очень быстро все (ОДНА из причин, что Punto Switcher мне не подходит, что тормозит у нее скорость переключения языка)

 
> Ещё если пользоваться не скомпилированной версией, то нажатие стоп\старт в меню вызывает ошибку:

Я закинул и в этот и другой проект в папку source нужный файл, а то действительно не все догадаются.


БОЛЬШОЕ СПАСИБО ЗА ЗАМЕЧАНИЯ !
Но, как работает, так работает. Уж очень сложно предусмотреть все случаи и особенно потом их проверить. 
Так что хотя бы неделю на тест этой версии надо, а там можно месяцами не замечать или заглючить может в какой-то программе, какой-то операционной системе и др.

**Comment by Lichtenshtein** [comment]
> Мой код проблемно работает с Punto Switcher, так как совместная работа не предназначена, уж тут могут быть конфликты.

Версии 1.3, 1.4 работали без конфликтов. Но, я видел, что к версии 2 вы практически полностью переписали код... большая работа, и настраивать под себя стало удобнее когда настройки вынесены в файл.

Я попробую перейти с Punto Switcher на https://github.com/Krot66/LangBarXX. В ней нельзя назначить привычную мне комбинацию для левой руки (Ctrl+space), а вариант с исправлением написанного по Capslock мне не подходит, т.к. на Capslock у меня переназначен Enter. Но всё равно я попробую, проблем с изменением регистра в этой программе нет (но есть другие проблемы).

> Скопируйте из нового файла настроек секцию «[LALTADD14]» там еще 14 горячих комбинации

Большое спасибо, буду осваивать.

**Comment by AndreyKaiu** [comment]
Если есть другие проблемы, то попробуйте проверить https://github.com/AndreyKaiu/Keyboard_Switcher_Kaiu - есть ли там?
Как раз от того, что переписал код, то все усложнилось (особенно виноват механизм изменения Ctrl на другую клавишу), а чем сложнее, тем хуже.
Программа разбита на модули и можно под себя изменить. Или если работает все нормально в Keyboard_Switcher_Kaiu  то можно добавить только нужное вам переключения - чисто для себя. Снова проверить и если работает, то добавить другой функционал.

**Comment by Lichtenshtein** [comment]
Только что проверил версию 2.0.3 Keybord_Assistant, проблема с Punto Switcher и изменением регистра пропала.

> попробуйте проверить https://github.com/AndreyKaiu/Keyboard_Switcher_Kaiu - есть ли там?

Дело в том, что Keybord_Assistant мне скорее нужен как инструмент для ввода нестандартных символов, и просто для более удобного ввода этих символов без необходимости переключаться между раскладками. Раскладки у меня всего 2, и Keybord_Assistant как продвинутый переключатель раскладок - это скорее полезное дополнение, которое в должной мере мною не востребовано. :)

**Comment by AndreyKaiu** [comment]
> Только что проверил версию 2.0.3 Keybord_Assistant, проблема с Punto Switcher и изменением регистра пропала.

Тут то да, но не гарантия на все возможные комбинации у Punto Switcher с моей программой. Тут тестировать можно долго.  Очень много всего перепроверить иногда надо, да и не профи я в этом скрипте....он так непривычно сделан, что просто вынос мозга иногда. 

> и просто для более удобного ввода этих символов без необходимости переключаться между раскладками.

По вашим словам это не скажешь «_вариант с исправлением написанного по Capslock мне не подходит, т.к. на Capslock у меня переназначен Enter._». А если многое не надо, то упростить программу можно и как раз всякие символы - это самое простое в этой программе, сложнее переназначение делать и переключатель языков, так как когда тестировал под 15 языков, то тормозить начинают многие программы переключения. Ну ладно, может 15 и не надо, но писали, что 4 языка используют переводчики, а большее кол. вряд ли. 
Так что описали бы, что конкретно используете, а то если проблемы будут, то проще написать мне на почту личную kaiu на mail.ru, да попробовал бы что-то подобрать более компактное.

**Comment by Lichtenshtein** [comment]
> По вашим словам это не скажешь «вариант с исправлением написанного по Capslock мне не подходит, т.к. на Capslock у меня переназначен Enter.»

Это же разные вещи: исправление неправильно введённого текста и фактическое расширение символьной раскладки.

В программе LangBarXX, которую я тестировал, можно исправлять введённые в неправильной раскладке строки по Capslock, который у меня уже занят, а стандартное Shift+BS в ней переназначить нельзя. В работе LangBarXX и Keybord_Assistant проблем нет, проблемы только с самой LangBarXX, она почему-то "съедает" 1 любой символ справа от каретки когда исправляешь текст вручную. Поэтому я думаю вернуться на Punto, раз с ним и Keybord_Assistant теперь проблем нет (из уже замеченных).

Вообще, Punto и мне с другими приложениями проблем доставлял. Например, он вешает намертво программу для заметок CIntaNotes, можно легко потерять важные заметки, если автоматическая резервная копия делалась несколько дней назад. Но отказаться от Punto сложно (я пробовал) - размер, скорость и удобство делают его незаменимым, к сожалению. Я думаю и мне и многим другим ещё много раз предстоит по кругу тестировать тот десяток "замен Punto", и в итоге возвращаться к Punto в надежде, что что-то из всего этого наконец доведут до нужного состояния.

> Так что описали бы, что конкретно используете

Ну, в-общем, вот такой "расклад" у меня сейчас :)

![Help_Russian](https://user-images.githubusercontent.com/13855295/216081484-421ca1b3-375f-4140-b7c0-4b5dbc909d6d.png)

Все потенциальные функции, использующие два новых модификатора Keybord_Assistant, фактически ни с чем не конфликтуют, и могут быть мне нужны. Мне интересно любое расширение функционала за счёт них. :)

Всё, что может в Keybord_Assistant конфликтовать с другими скриптами и программами, я отключаю... Функцию изменения регистра выделенных символов (на строчные, прописные, инверсия, на первые заглавные, регистр как в предложении) у меня выполняет другая программа (встроенная функция Charu3 + ahk скрипты из CLCL_Ahk, либо LangBarXX). Транслитерацией никогда не пользовался (хотя может понадобиться). Как замена мыши - я пробовал, интересно, и почти удобно, если бы не через Tab. Языка в системе у меня только 2, поэтому функционал продвинутого менеджера-переключателя языка мне не нужен. Я не задумываясь переключаю язык только по Alt+Shift, хотя по одиночному нажатию RAlt - тоже здорово удобно. Так что, как я уже сказал, сейчас Keybord_Assistant мне наиболее полезен как инструмент для ввода стандартных и нестандартных символов - как расширитель стандартной раскладки. Нужно ли писать и выносить эти функции в отдельную программу, если в версии 2.0 всё можно отключить через .ini... не знаю, вам видней. Я бы сам почитал отзывы других людей, узнать для чего они используют программу.

**Comment by AndreyKaiu** [comment]
Да, серьезное у вас применение этого всего. Я тут даже взял паузу подумать и то нет времени проанализировать программы Charu3 и др. Я мало пользуюсь вставками, точнее если они есть, то и так в редакторах они есть, как подсказки. Недавно потребовалось, то не стал ничего добавлять в свою программу, когда есть разные. Мне понравилась простое решение CLCL, глючило с моим решением, понял, что во многих других подход сделан через RCtrl+С а у меня его запретили. Так что автору описал, он быстро подправил. Так что был смысл переделать, благо код был открыт https://github.com/AndreyKaiu/CLCL-EN-RU-JP-Plugins - так что теперь снова моежет появится русская страничка у автора...ну, в принципе она никуда не убегала, скрыто она есть с 2005 года https://nakka.com/soft/clcl/index_rus.html - но по главной если зайти, то не найдете, так как не делал кто-то там. Я просто добавил возможность русского и любого другого....ну, там не удобно перевод делать, а универсальную если захочет автор, то сделает. Почему же не внедрил что-то у себя? Да долго, это раз, да и не всем надо скрипты или по безопастности запретить могут. А эту программу может применить тот, кому надо только вот эта часть. Вот и у меня в программе модульность уже, вы же применяете множество программ. А в скриптах отлавливать по #if такое себе занятие, так как ловит только комбинации, а не все, что там. На новую версию языка я не хочу это переписывать, на все это время надо. Вот поэтому все на гитхабе, чтобы кому надо, то менял код, просто ветку создадут, а там авось что-то полезное выйдет для кого-то.

> Транслитерацией никогда не пользовался (хотя может понадобиться). 

Почти постоянно, когда надо закинуть файлы, не доверяю это скриптам хостинга. 

> Как замена мыши - я пробовал, интересно, и почти удобно, если бы не через Tab.

Вообще не использую, это только крайний вариант, действительно если поломается мышь :) А TAB...ну так ничего больше нет, не зря же придумали «TrackPoint — это тензометрический манипулятор, управляющий курсором на экране твоего ноутбука. Это между GHB клавиш»

> Capslock у меня переназначен Enter

Опасное решение, сколько людей жаловались на случайное нажатие CapsLock, что его даже отключали или переназначали так же как LShift - что и у меня есть.
Но тут такое дело, что если вам это надо, то надо :), а если постоянно, то я писал, что проще тогда использовать специальную прогу для переназначений («KeyTweak»), но тут тоже проблемы могут быть, так как учитывать надо иногда схемное решение клавиатур, а то у меня вон на CapsLock стоит LCtrl, а схема клавиатуры такова, что LCtrl+LShift+S работать не будет.

> Функцию изменения регистра выделенных символов (на строчные, прописные, инверсия, на первые заглавные, регистр как в предложении) у меня выполняет другая программа (встроенная функция Charu3 + ahk скрипты из CLCL_Ahk, либо LangBarXX).

Поразбираюсь как-то, но уже говорил, что больше на сторонние редакторы надеюсь. хоть тоже самое может почти любой, даже для txt Notepad++ чего только не умеет. А, да, не умеют они переключать языки, так как это завязано на систему и взаимодействие между программами.

**Comment by Lichtenshtein** [comment]
> Поразбираюсь как-то

Если хотите, могу скинуть вам этот "колхоз"... чтобы не пришлось рыскать.
https://disk.yandex.ru/d/zyYY5BlIFLGYgA

Ссылки, откуда брал.

https://forum.ru-board.com/topic.cgi?forum=5&topic=50494#1
CLCL_AHK - менеджер буфера обмена плюс расширенная обработка текста средствами Autohotkey и AutoIt

https://github.com/hi5/CL3
Minimal clipboard caching utility inspired by CLCL

https://github.com/itagagaki/charu3-SE
Charu3 fork

https://github.com/stefansundin/altdrag
Easily drag windows when pressing the alt key

https://github.com/Krot66/LangBarXX
Индикация раскладки у курсора и ее исправление (замена Punto Switcher)

https://github.com/randyrants/sharpkeys
SharpKeys is a utility that manages a Registry key that allows Windows to remap one key to any other key

**Comment by AndreyKaiu** [comment]
> Если хотите, могу скинуть вам этот "колхоз"... чтобы не пришлось рыскать.

СПАСИБО! 
Пока правда занят тоже бесплатной деятельностью, хочу вот привести в порядок https://www.softportal.com/software-12305-nachala-elektroniki.html и застрял отлавливая пробел лишний в IDA дизассемблере, а так как я не спец в этом, то выходит медленно :( Но к выходным видно точно выложу, по сути все готово, а подобных прог мало...или крутые онлайн,  или просто схемные решения, а не такое «ламповое» :)

**Comment by Lichtenshtein** [comment]
> СПАСИБО!

Если скачали мой архив, удалите пожалуйста. В нём могли остаться личные данные. Вот новая ссылка:

https://disk.yandex.ru/d/wW5d9tkd7D53AA

> застрял отлавливая пробел лишний в IDA дизассемблере, а так как я не спец в этом, то выходит медленно

Здорово, полезный софт. Желаю удачи в отлове :)

**Comment by AndreyKaiu** [comment]
> В нём могли остаться личные данные

Вот поэтому особо не доверяю этим программ-буферам. У автора CLCL можно настроить не обращать внимание на некоторые окна...не знаю как тут, всё не добрался. Так что тем и понравился CLCL, да можно назначить не сохранять историю и др. Может и скрипт хорошо...но мне его было делать лень, уж очень все долго, если нормально делать.

> Здорово, полезный софт. Желаю удачи в отлове :)

Спасибо, как раз видно пожелание и помогло, что отловил вчера.
Да вот только сейчас доделал, да что-то чиркнул по описанию на сайте.
Так что можно глянуть тут https://kaiu.narod.ru/E/E.html 
Найти бы еще кто бы хоть проверил серьезно...но это вряд ли, уж сколько лет валяется глючно тут https://www.softportal.com/software-12305-nachala-elektroniki.html и то ничего с 2008 года не делали.

Ладно, иду спать, а то достало уже это программирование :), не тот возраст сидеть до утра.

**Comment by AndreyKaiu** [comment]
> Если хотите, могу скинуть вам этот "колхоз"... чтобы не пришлось рыскать. https://disk.yandex.ru/d/zyYY5BlIFLGYgA
> https://forum.ru-board.com/topic.cgi?forum=5&topic=50494#1 CLCL_AHK - менеджер буфера обмена плюс расширенная обработка текста средствами Autohotkey и AutoIt

Я тут по этому покопался, пока на форум отписал, если будут желающие тестить, то хорошо

http://forum.ru-board.com/topic.cgi?forum=5&topic=50494&start=20#lt
